### ISSUE TITLE
3DR radio flashing error

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#991] opened 2016-11-28 12:37 UTC
(terminal output)
```
Flashing with firmware
./sik_uploader/firmware/1.9/radio~hm_trp.ihx
..............................uploading to port /dev/ttyUSB0
Connecting to /dev/ttyUSB0
Traceback (most recent call last):
  File "./sik_uploader/sik_uploader.py", line 278, in <module>
    if not up.check():
  File "./sik_uploader/sik_uploader.py", line 237, in check
    self.autosync()
  File "./sik_uploader/sik_uploader.py", line 197, in autosync
    import fdpexpect, time , pexpect
ImportError: No module named fdpexpect

Complete 1
```
pexpect is installed using pip install..

**Comment by AndKe** [comment] 2017-02-02 22:13
also, when at it, please add option for custom firmware.

**Comment by RHHoek** [comment] 2017-02-22 18:54
I solved this issue (Ubuntu 16:10) by installing these packages:
apt-get install python-serial python-pexpect

and changing sik_uploader/sik_uploader.py:

line 197,198
         import fdpexpect, time , pexpect
         ser = fdpexpect.fdspawn(self.port.fileno(), logfile=sys.stdout)
to:
         import pexpect, time , pexpect.fdpexpect
         ser = pexpect.fdpexpect.fdspawn(self.port.fileno(), logfile=sys.stdout)
line 200
             self.port.setBaudrate(self.atbaudrate)
to:
             self.port.baudrate=self.atbaudrate
line 219
                     self.port.setBaudrate(115200)
to:
                     self.port.baudrate=115200
line221
             except fdpexpect.TIMEOUT:
to:
             except pexpect.fdpexpect.TIMEOUT:
line 224
             self.port.setBaudrate(115200)
to:
             self.port.baudrate=115200

**Comment by Arne-W** [comment] 2017-02-22 21:38
Nice :+1: 
It would be great if you could make a pull request.

**Comment by RHHoek** [comment] 2017-03-02 15:57
I am not ready to send you a pull request at the moment (need to find out in detail how this works). So for the moment I can only provide the changed file.
[sik_uploader.py.zip](https://github.com/ArduPilot/apm_planner/files/814350/sik_uploader.py.zip)

**Comment by AndKe** [comment] 2017-03-02 18:44
@RHHoek , works fine
@Arne-W  here's a PR https://github.com/ArduPilot/apm_planner/pull/1009
- where should I put the dependencies ?

**Comment by Arne-W** [comment] 2017-03-02 19:42
Awesome guys! 
The dependencies - good question - perhaps @billbonney knows :wink:

**Comment by AndKe** [comment] 2017-03-02 21:29
added dependencies as best I could  :)

**Comment by RHHoek** [comment] 2017-03-08 18:11
perhaps you also need to add these dependencies in de README.md ?

**Comment by AndKe** [comment] 2017-03-08 18:27
Good point , done :)

**Comment by AlivaDot** [comment] 2017-03-15 11:20
Hello!
I received this problem too.
But find another solution for OSX (10.12.3)
First of all install some packages:
```
sudo easy_install pip
sudo python -m pip install pyserial
sudo python -m pip install pexpect
```
(pyserial because error was at step "import sys, argparse, binascii, serial, glob")
And some changes in sik_uploader.py line 197
```
- import fdpexpect, time , pexpect
+ import time , pexpect
+ from pexpect import fdpexpect
```

**Comment by Arne-W** [comment] 2017-07-01 10:02
@AlivaDot is your comment just an alternative solution, or does the solution provided by @AndKe and @RHHoek solve your Problem too?

**Comment by Arne-W** [comment] 2017-07-16 12:46
@AlivaDot Ping :smiley: 
I will close this issue in the next days if nobody stops me....

**Comment by Arne-W** [comment] 2017-07-23 09:29
All right I am closing this now assuming the problem is solved.

**Closed by Arne-W** 2017-07-23 09:29 UTC
