### ISSUE TITLE
.tlog playback pause;  X-axis time continiue to grow while paused.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/apm_planner#549] opened 2014-12-13 22:53 UTC
reproduce:
Please load a .tlog , play it , let's say you observe altitude. 
Pause the playback for a minute.
Resume.  Observe that the graph time continued to increase , and you have a very stretched graph.

**Comment by Arne-W** [comment] 2017-03-20 14:28
is a duplicate of #589

**Closed by Arne-W** 2017-03-20 14:28 UTC
Labels: bug, Graphing
