### ISSUE TITLE
Unable to change log directory

### ISSUE THREAD

**Issue by badaniels** [ArduPilot/apm_planner#1044] opened 2017-05-22 12:55 UTC
On APM Planner there is the option to set which directory the log files are saved to. However, you are unable to change these away from the default setting. Although the menu does allow to change the directory, it does not enable this change of directory and it does not save this setting for next time the app is launched. 

I am trying to change the tlogs directory to a dropbox so that I can automatically have my flight data saved to a shared folder.

**Comment by pepak** [comment] 2017-06-24 19:59
Same bug as [this](https://github.com/ArduPilot/apm_planner/issues/1002).

**Comment by Arne-W** [comment] 2017-07-01 09:16
@pepak thanks for testing.
@badaniels I am closing this issue cause its a duplicate and I am not able to reproduce it with the current master.

**Closed by Arne-W** 2017-07-01 09:16 UTC
Labels: duplicate
