### ISSUE TITLE
OSX APM - Crash on Log Open

### ISSUE THREAD

**Issue by Fireycold** [ArduPilot/apm_planner#916] opened 2016-03-13 20:43 UTC
Any time I try and open a log that contains data, APM crashes. If the log is blank, it will open the log and display a blank log, but if there is any information contained in the file, the program will crash. Mission Planner on Windows does not have this issue, this issue occurs with about a dozen different logs, its not specific to a given log.

Using the 2.0.19 nightly build, and the current 2.0.18 release, the error still happens. 

Any help is much appreciated, thanks!

see crash log here https://gist.github.com/billbonney/f87b60b1fd0a1dffb83d

**Comment by Arne-W** [comment] 2016-03-14 16:51
Could you please upload one of the logs that leads to a crash?
It looks like you are loading a *.tlog. Does this happen on loading flash logs (*.bin) too?

I will take a look. On my Linux machine everything seems to work - but perhaps with your logfile I can reproduce the crash.

**Comment by billbonney** [comment] 2016-03-14 17:47
@Fireycold Please post a log, I just tried a 60Mbyte tlog file on OSX and it was fine

You can email me a link to log, if you want to keep it private. (see profile for email address)

**Comment by Fireycold** [comment] 2016-03-14 20:25
I don't have any .bin files to test it with, I have only been working with 3DR Solo generated .tlogs

If you guys have a log you know is working on your end, I can test it on mine.





[4 Logs.zip](https://github.com/diydrones/apm_planner/files/172797/4.Logs.zip)

**Comment by Arne-W** [comment] 2016-03-15 00:22
I could reproduce it and made a small fast fix - is not perfect but fixes the crash.
Thanks for the logs.

**Comment by Fireycold** [comment] 2016-03-15 01:18
When will these modifications be reflected in the daily build?

On Mon, Mar 14, 2016 at 5:22 PM, Arne Wischmann <notifications@github.com>
wrote:

> I could reproduce it and made a small fast fix - is not perfect but fixes
> the crash.
> Thanks for the logs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/diydrones/apm_planner/issues/916#issuecomment-196584307
>



-- 
Regards,

Andrew

**Comment by billbonney** [comment] 2016-03-15 02:01
@Fireycold now ;)

**Comment by Arne-W** [comment] 2017-01-30 00:11
As the log handling is completely rewritten this bug should be fixed...

**Closed by Arne-W** 2017-01-30 00:11 UTC
Labels: bug
