### ISSUE TITLE
Empty "Standard Params" and  "Advanced Params"

### ISSUE THREAD

**Issue by JulienGAMartin** [ArduPilot/apm_planner#934] opened 2016-04-21 10:47 UTC
Hi
since I installed the latest version 2.0.20 the "Standard Params" and "Advanced Params" tabs in "Config/Tuning" are empty.  In the "Full Parameters list" tab I can see all the parameters but withou any description.
I can see everything in the "Extended tuning" tab
Tested on two different PCs with Ubuntu 15.10 using the x64 build from http://discuss.ardupilot.org/t/download-latest-apm-planner-2-0-20-and-other-releases/8268

**Comment by martinjuju** [comment] 2016-04-21 13:44
I want to add that this is a packaging problem since it is solved if I build it from source

**Comment by billbonney** [comment] 2016-04-21 14:09
The file with the descriptions is also downloaded. It should not matter if it is in the package

We have had similar reports but I haven't been able to reproduce.

**Comment by martinjuju** [comment] 2016-04-21 15:14
Oddly enough I repeated the problems on 3 different Ubuntu 15.10 system using the .deb package provided.
Building my own .deb (using debuilt) and using the deb file on the 3 systems solved the problem.

**Comment by dcarpy** [comment] 2016-04-22 15:53
Is it the same user you build with, run with and installed with?  Just wondering if it's a permissions problem with the parameters file location.
I'm not able to reproduce either.  Looks good on my box. :-)

**Comment by salomatu** [comment] 2016-05-26 20:59
I think I have something fitting to this description. I found that when the parameters list is downloaded, the file contains the 302 response from the server and apparently whichever component is responsible for the download fails to recurse into the proper address of the file.
I use 2.0.20 and tried to revert to older version, but of course that didn't help since the location of the file has changed.
I circumvent this problem by downloading the file manually with wget each and every time I start the software.
Platform is OSX 10.9.5.

**Comment by billbonney** [comment] 2016-05-26 21:20
it's fixed here 5c81f622e212be05b248e0fba4bb8b45c64b609e

**Comment by Arne-W** [comment] 2017-03-29 14:51
As this is fixed on master - I will close it.

**Closed by Arne-W** 2017-03-29 14:51 UTC
Labels: bug
